Basic Features
fuseio/fusebox-web-sdk pull request #1
Opened 2023-10-25 13:12 UTC by MayankMittal1

2023-10-26 10:38 UTC, MusabShakeel576 commented
@MayankMittal1 which commands are you using to run examples files? It's throwing the following error while running `/example/address.js`:

```bash
fuse_wallet_web_sdk/node_modules/@ethersproject/bytes/lib/index.js:9
return !!(value.toHexString);
```

Btw a few small changes which could optimize this package/sdk:
- Create `.npmignore` file (or use `files` attribute in `package.json`) and add `/src` and `/example` folders into it to reduce the bundle size.
- Put `/dist` in `.gitignore`.

2023-10-30 10:18 UTC, leonprou commented on src/constants/variables.ts
> +  static FUSE_CHAIN_ID = 122;
How can we run the SDK on Spark or staging if those are hard coded?

2023-10-30 10:18 UTC, leonprou commented on src/constants/variables.ts
> +  static FUSE_CHAIN_ID = 122;
@SametSahin10 @NikolayRn
We have the same issue with a mobile SDK, right?

2023-10-31 11:01 UTC, leonprou requested changes
Looks good,
Please see my comments @MusabShakeel576 , @MayankMittal1 .
Also I want to loop in @SametSahin10 for the compability with the mobile version

2023-10-31 11:01 UTC, leonprou commented on src/etherspot.ts
> +export const ETHERSPOT_FACTORY = '0x7f6d8F107fE8551160BD5351d5F1514A6aD5d40E';
put to this in a config

2023-10-31 11:01 UTC, leonprou commented on src/modules/staking.ts
> +      const response = await this._axios.post('/v0/staking/unstake', unstakeRequestBody);
There's no reason no to do this on the Dapp side

2023-10-31 11:01 UTC, leonprou commented on src/modules/staking.ts
> +      const response = await this._axios.post('/v0/staking/stake', stakeRequestBody);
There's no reason no to do this on the Dapp side

2023-10-31 11:01 UTC, leonprou commented on src/sdk.ts
> +  public static defaultTxOptions = new TxOptions('1000000', 10, false);
Can we explain those values?
I wonder if they should be part of the config

2023-10-31 11:01 UTC, leonprou commented on src/utils/contracts.ts
> +  public static signOffChain(
That's a method for the old SDK

2023-10-31 11:01 UTC, leonprou commented on src/utils/contracts.ts
> +export class ContractUtils {
Hi @SametSahin10 
Are methods in this class are needed in the new SDK? Looks to me that some of them related to the old one

2023-10-31 12:58 UTC, SametSahin10 commented on src/constants/variables.ts
> +  static FUSE_CHAIN_ID = 122;
This constants exists in the mobile SDK but it's not used anywhere. @leonprou

2023-10-31 13:02 UTC, SametSahin10 commented on src/utils/contracts.ts
> +export class ContractUtils {
Some of them are used in the new SDK, yes. Some of the are only used by the old SDK. For example:

- `encodedDataForContractCall`
- `signOffChain`

@leonprou

2023-10-31 15:19 UTC, MusabShakeel576 commented on src/constants/variables.ts
> +  static FUSE_CHAIN_ID = 122;
@leonprou fixed, added env to Variables to make them soft coded in a new [Fix Basic Features PR](https://github.com/fuseio/fuse_wallet_web_sdk/pull/2).

2023-10-31 15:20 UTC, MusabShakeel576 commented on src/etherspot.ts
> +export const ETHERSPOT_FACTORY = '0x7f6d8F107fE8551160BD5351d5F1514A6aD5d40E';
@leonprou updated.

2023-10-31 15:20 UTC, MusabShakeel576 commented on src/modules/staking.ts
> +      const response = await this._axios.post('/v0/staking/unstake', unstakeRequestBody);
@leonprou fixed.

2023-10-31 15:20 UTC, MusabShakeel576 commented on src/modules/staking.ts
> +      const response = await this._axios.post('/v0/staking/stake', stakeRequestBody);
@leonprou fixed.

2023-10-31 15:21 UTC, MusabShakeel576 commented on src/sdk.ts
> +  public static defaultTxOptions = new TxOptions('1000000', 10, false);
@leonprou fixed, move them into Variables and remove TxOptions class.

2023-10-31 15:22 UTC, MusabShakeel576 commented on src/utils/contracts.ts
> +  public static signOffChain(
@leonprou removed.

2023-11-06 09:56 UTC, leonprou commented on src/utils/contracts.ts
> +export class ContractUtils {
Thanks @SametSahin10 
@MusabShakeel576 please delete encodedDataForContractCall also

2023-11-06 09:57 UTC, leonprou commented on src/constants/variables.ts
> +  static FUSE_CHAIN_ID = 122;
Thanks Musab

2023-11-06 10:14 UTC, MusabShakeel576 commented on src/utils/contracts.ts
> +export class ContractUtils {
@leonprou deleted https://github.com/fuseio/fuse_wallet_web_sdk/pull/2/commits/9c1d9c64d43de502e7970987af569aff6972c641

2023-11-07 12:54 UTC, MusabShakeel576 reviewed
LGTM

2023-11-19 09:38 UTC, leonprou approved these changes

2023-11-19 10:16 UTC, merged